### ISSUE TITLE
Consider Privatizing Waffle Boards

### ISSUE THREAD

**Issue by lisaratner** [lisaratner/long-beach-analytics#115]

**Comment by lisaratner** [comment]
Heidi brought up concerns with having this public

**Comment by lisaratner** [comment]
Trello can be the private tracker.
When we switch to sustainability we can switch over

**Comment by rossettistone** [comment]
Per our conversation yesterday (so we can close this one out):

Because this (and other) Waffle boards are simply an interface for GitHub issues, and those GitHub issues are part of open source repositories, there is no way to privatize these Waffle boards without taking the code closed-source.

Migrating to another project management tool *independent* of GitHub (like Trello) could be an option.

I fully support the eventual owner of this (and other) repos choosing a set of project management tools that make sense to them. At this time, though, I don't see a compelling reason to move. I therefore suggest no change at this time.
