### ISSUE TITLE
Sync Keen.io with Dasheroo

### ISSUE THREAD

**Issue by lisaratner** [lisaratner/long-beach-analytics#45]

**Comment by lisaratner** [comment]
Add Keen to search bar

**Comment by lisaratner** [comment]
one solution is to dump keen.io data to a google spreadsheet.

**Comment by rossettistone** [comment]
Can you tell me a little more about exactly which data we're trying to get from Keen into Dasheroo?

**Comment by lisaratner** [comment]
1) Most checked off action items
2) What step in starting a business was clicked on the most / least
3) Resource Matching Metrics: Which were most popular (clicked on)
4) (Eventually) RM which were the most saved, which were most shared

**Comment by rossettistone** [comment]
To my relative bafflement, it seems like Dasheroo only allows histograms on their standard "Custom" integration, which won't do the trick for the metrics above, as most of those look like bar/column charts. The "Push API" looks like it'll support other chart types, though.

I've filed feedback with Dasheroo that they should consider supporting more chart types with the "Custom" integration type. 

I'll dig into the Push API now. Considerably larger hassle than the Custom method, but I'm optimistic that I can use BizPort as a proxy to get Keen data over to Dasheroo. Weird, but doable.

**Comment by rossettistone** [comment]
So the Push API is...underwhelming. Documentation is spotty and inaccurate.

Also, to use the Push API, the app will need to have scheduled (e.g. daily) tasks, run on a cronjob or similar. Doesn't seem worth the calories to do this on the city server at this time, since we're moving to cloud hosting at some point soon here.

My thought is to backlog this story until we're on the final hosting provider (https://github.com/rossettistone/longbeach2016/issues/323). In the meantime, I'll put together the charts above as views on `/admin/dashboard` so that we can at least look at them internally.

**Comment by rossettistone** [comment]
Dasheroo is now defunct. Closing.
